version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - durationcheck
    - exhaustive
    - gocritic
    - godot
    - gosec
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - funlen
    - ireturn
    - lll
    - mnd
    - testpackage
    - varnamelen
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io.Copy
        - fmt.Fprintf
        - fmt.Fprintln
    exhaustive:
      default-signifies-exhaustive: false
    gocritic:
      enabled-checks:
        - nilValReturn
        - weakCond
        - sloppyReassign
        - unnecessaryBlock
        - appendCombine
        - commentedOutCode
    gosec:
      excludes:
        - G104
        - G304
        - G306
    misspell:
      locale: US
    nakedret:
      max-func-lines: 10
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: waitgroup-by-value
        - name: unconditional-recursion
        - name: cognitive-complexity
          arguments:
            - 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocritic
        path: _test\.go
      - linters:
          - all
        path: .*_generated\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
  rules:
    - linters:
        - godot
        - misspell
        - whitespace
      severity: warning
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
