# .goreleaser.yml — Cross-platform release configuration for Stricture.
project_name: stricture

before:
  hooks:
    - go mod tidy

builds:
  - id: strict
    main: ./cmd/strict
    binary: strict
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    builds:
      - strict
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: git
